name: Continuous Integration
on:
  push: { branches: [ main ] }
  pull_request: { }
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '^1.24'
      - run: go build
        env:
          CGO_ENABLED: 0
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:26.7
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - '3306:3306'
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '^1.24'
      - name: Setup MySQL
        run: |
          while true;
          do
            if [ "$(mysql -h 127.0.0.1 -u root -N -s -e 'select 1' 2> /dev/null)" == "1" ];
            then
              break
            fi
            sleep 1
          done

          mysql -h 127.0.0.1 -u root -e 'create database cbng; create database enwiki_p'

          mysql -h 127.0.0.1 -u root cbng < cluebot.sql
          mysql -h 127.0.0.1 -u root enwiki_p < .github/enwiki_p.sql
      - run: go test
        env:
          BOT_CFG: .github/config.yaml
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '^1.24'
      - run: go vet
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '^1.24'
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
