name: Continuous Integration
on:
  push: { branches: [ main ] }
  pull_request: { }
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - run: go build
        env:
          CGO_ENABLED: 0
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - '3306:3306'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - name: Setup MySQL
        run: |
          while true;
          do
            if [ "$(mysql -h 127.0.0.1 -u root -N -s -e 'select 1' 2> /dev/null)" == "1" ];
            then
              break
            fi
            sleep 1
          done

          mysql -h 127.0.0.1 -u root -e 'create database cbng; create database enwiki_p'

          mysql -h 127.0.0.1 -u root cbng < cluebot.sql
          mysql -h 127.0.0.1 -u root enwiki_p < .github/enwiki_p.sql
      - run: go test
        env:
          BOT_CFG: .github/config.yaml
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - run: go vet
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - uses: golangci/golangci-lint-action@v6
